/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.HealthcareAccountantRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.InsuranceCompanyEnterprise;
import Business.Insurance.Insurance;
import Business.InsuranceCustomer.InsuranceCustomer;
import Business.Network.Network;
import Business.Organization.AccountantOrganization;
import Business.Organization.InsuranceAgentOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.AccountantBillingRequest;
import Business.WorkQueue.InsuranceWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.text.DecimalFormat;
import java.util.List;
import java.util.UUID;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author bunty
 */
public class AccountantProcessRequestJPanel extends javax.swing.JPanel {

    private JPanel jPanel;
    private UserAccount usrAcnt;
    private Enterprise entrpz;
    private AccountantOrganization acntOrg;
    private AccountantBillingRequest acntBillingReq;
    private EcoSystem ecosystem;
    private double pyblAmnt;

    /**
     * Creates new form AccountantWorkRequestJPanel
     */
    AccountantProcessRequestJPanel(JPanel userProcessContainer, UserAccount userAccount, AccountantBillingRequest request, Enterprise enterprise, EcoSystem ecoSystem) {
        initComponents();
        this.jPanel = userProcessContainer;
        this.usrAcnt = userAccount;
        this.entrpz = enterprise;
        this.acntOrg = acntOrg;
        this.acntBillingReq = request;
        this.ecosystem = ecoSystem;
        populate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        sndReqFrInsrbtn = new javax.swing.JButton();
        ssnTxt = new javax.swing.JTextField();
        InsrPlcyNumTxt = new javax.swing.JTextField();
        pyblAmntTxt = new javax.swing.JTextField();
        frstNmTxt = new javax.swing.JTextField();
        billAmntTxt = new javax.swing.JTextField();
        lstNmTxt = new javax.swing.JTextField();
        plcyNumTxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        insrClmAmntTxt = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();
        clctAmntBtn = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(238, 0, 51));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Process Billing Request Area");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("SSN");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("FirstName");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("LastName");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Bill Amount");

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Insurance Policy Name");

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Payable Amount");

        sndReqFrInsrbtn.setBackground(new java.awt.Color(0, 153, 255));
        sndReqFrInsrbtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        sndReqFrInsrbtn.setText("Charge Amount / Initiate Claim Request");
        sndReqFrInsrbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sndReqFrInsrbtnActionPerformed(evt);
            }
        });

        ssnTxt.setEditable(false);

        InsrPlcyNumTxt.setEditable(false);

        pyblAmntTxt.setEditable(false);

        frstNmTxt.setEditable(false);

        billAmntTxt.setEditable(false);

        lstNmTxt.setEditable(false);

        plcyNumTxt.setEditable(false);

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Policy Number");

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("Insurance Claim Amount");

        insrClmAmntTxt.setEditable(false);

        backJButton.setBackground(new java.awt.Color(204, 204, 204));
        backJButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        clctAmntBtn.setBackground(new java.awt.Color(0, 153, 255));
        clctAmntBtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        clctAmntBtn.setText("Complete Patient Transaction");
        clctAmntBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clctAmntBtnActionPerformed(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Accountant.gif"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(backJButton)
                        .addGap(104, 104, 104)
                        .addComponent(jLabel1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap(136, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(12, 12, 12)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel6))
                                    .addGap(52, 52, 52)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(InsrPlcyNumTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(plcyNumTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(52, 52, 52)
                                        .addComponent(pyblAmntTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(52, 52, 52)
                                        .addComponent(insrClmAmntTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(77, 77, 77)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5))
                                    .addGap(52, 52, 52)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(frstNmTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lstNmTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(billAmntTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(ssnTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(48, 48, 48)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(86, 86, 86)
                            .addComponent(sndReqFrInsrbtn)
                            .addGap(32, 32, 32)
                            .addComponent(clctAmntBtn))))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(plcyNumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(InsrPlcyNumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(ssnTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(frstNmTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(lstNmTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(billAmntTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(insrClmAmntTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(pyblAmntTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sndReqFrInsrbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clctAmntBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(90, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void sndReqFrInsrbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sndReqFrInsrbtnActionPerformed
        String policyNumber = acntBillingReq.getPatient().getInsuranceCustomer().getInsPlcyNo();
        String ssn = acntBillingReq.getPatient().getSsn();
        String policyName = acntBillingReq.getPatient().getInsuranceCustomer().getIns().getPlcyNm();
        String insuranceCompany = acntBillingReq.getPatient().getInsuranceCustomer().getIns().getInsCmpny();
        double claimAmount = Double.parseDouble(insrClmAmntTxt.getText());
        double billAmount = acntBillingReq.getBillingAmt();
        if (("Patient Transaction Completed").equals(acntBillingReq.getStatus())) {
            JOptionPane.showMessageDialog(null, "Insurance request sent for claim");
            return;
        }
        Insurance insr = new Insurance(policyName, insuranceCompany, claimAmount);
        insr.setCvrg(acntBillingReq.getPatient().getInsuranceCustomer().getIns().getCvrg());
        InsuranceCustomer insrCus = new InsuranceCustomer(insr, policyNumber);
        insrCus.setCustFrstNm(frstNmTxt.getText().trim());
        insrCus.setCustLstNme((lstNmTxt.getText().trim()));

        InsuranceWorkRequest isnrWrkReq = new InsuranceWorkRequest();
        isnrWrkReq.setInsCmpny(insuranceCompany);
        isnrWrkReq.setPlcyNo(policyNumber);
        isnrWrkReq.setPlcyNm(policyName);
        isnrWrkReq.setSsn(ssn);
        isnrWrkReq.setClaimAmt(claimAmount);
        isnrWrkReq.setBillAmt(billAmount);
        isnrWrkReq.setHealthCtr(entrpz.getName());

        isnrWrkReq.setSender(usrAcnt);
        isnrWrkReq.setStatus("Sent");
        isnrWrkReq.setInsCust(insrCus);

        Organization org = null;
        InsuranceCompanyEnterprise matchedInsuranceCompany = null;

        List<Network> networks = ecosystem.getNetworks();
        for (Network network : networks) {
            List<Enterprise> enterprises = network.getEntDir().getEntList();
            for (Enterprise enterprise : enterprises) {
                if (enterprise.getName().equalsIgnoreCase(acntBillingReq.getPatient().getInsuranceCustomer().getIns().getInsCmpny())) {
                    matchedInsuranceCompany = (InsuranceCompanyEnterprise) enterprise;
                }
            }
        }

        for (Organization organization : matchedInsuranceCompany.getOrgDir().getOrganizations()) {
            if (organization instanceof InsuranceAgentOrganization) {
                org = organization;
                break;
            }
        }
        if (org != null) {
            org.getWrkQ().getWorkRequests().add(isnrWrkReq);
            usrAcnt.getWrkQ().getWorkRequests().add(isnrWrkReq);
            acntBillingReq.setStatus("Patient Transaction Completed");
            acntBillingReq.getPatient().setIsTrtmntdone(true);
            JOptionPane.showMessageDialog(null, "Money received from patient: " + String.format("%.2f", String.valueOf(pyblAmnt)) + ". Insurance Claim Request Raised Successfully for amount:" + claimAmount);
            sndReqFrInsrbtn.setEnabled(false);
        }


    }//GEN-LAST:event_sndReqFrInsrbtnActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        jPanel.remove(this);
        Component[] componentArray = jPanel.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ProcessMedicalBillingsJPanel pmbjp = (ProcessMedicalBillingsJPanel) component;
        pmbjp.populateTable();
        pmbjp.populateInsuranceClaimTable();
        CardLayout layout = (CardLayout) jPanel.getLayout();
        layout.previous(jPanel);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void clctAmntBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clctAmntBtnActionPerformed
        CardLayout layout = (CardLayout) jPanel.getLayout();
        jPanel.add("EmailBillingInformationToPatient", new EmailBillingInformationToPatient(jPanel, acntBillingReq));
        layout.next(jPanel);
    }//GEN-LAST:event_clctAmntBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField InsrPlcyNumTxt;
    private javax.swing.JButton backJButton;
    private javax.swing.JTextField billAmntTxt;
    private javax.swing.JButton clctAmntBtn;
    private javax.swing.JTextField frstNmTxt;
    private javax.swing.JTextField insrClmAmntTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField lstNmTxt;
    private javax.swing.JTextField plcyNumTxt;
    private javax.swing.JTextField pyblAmntTxt;
    private javax.swing.JButton sndReqFrInsrbtn;
    private javax.swing.JTextField ssnTxt;
    // End of variables declaration//GEN-END:variables

    private void populate() {
        String policyNumber = acntBillingReq.getPatient().getInsuranceCustomer().getInsPlcyNo();
        DecimalFormat df2 = new DecimalFormat("#.##");
        double coverage = acntBillingReq.getPatient().getInsuranceCustomer().getIns().getCvrg();
        double billAmount = acntBillingReq.getBillingAmt();
        String ssn = acntBillingReq.getPatient().getSsn();
        String policyName = acntBillingReq.getPatient().getInsuranceCustomer().getIns().getPlcyNm();
        String insuranceCompany = acntBillingReq.getPatient().getInsuranceCustomer().getIns().getInsCmpny();
        double claimAmount = (coverage * billAmount) / 100;
        pyblAmnt = billAmount - claimAmount;

        plcyNumTxt.setText(policyNumber);
        ssnTxt.setText(ssn);
        frstNmTxt.setText(acntBillingReq.getPatient().getPatFrstNm());
        lstNmTxt.setText(acntBillingReq.getPatient().getPatLstNm());
        billAmntTxt.setText(String.valueOf(billAmount));
        InsrPlcyNumTxt.setText(policyName);
        insrClmAmntTxt.setText(String.valueOf(claimAmount));
        pyblAmntTxt.setText(String.valueOf(df2.format(pyblAmnt)));

        if (claimAmount > 0) {
            sndReqFrInsrbtn.setEnabled(true);
            clctAmntBtn.setEnabled(false);
        } else {
            clctAmntBtn.setEnabled(true);
            sndReqFrInsrbtn.setEnabled(false);
        }

    }
}
