/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DoctorRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.AccountantOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.AccountantBillingRequest;
import Business.WorkQueue.PatientTreatmentWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author bunty 
 */
public class RequestBillingJPanel extends javax.swing.JPanel {

    private JPanel jPanel;
    private UserAccount usrAcnt;
    private Enterprise entrpz;
    private PatientTreatmentWorkRequest pntTrtmntWrkReq;
    private EcoSystem ecoSystem;
    private double cnsltChrg = 50;

    /**
     * Creates new form RequestBillingJPanel
     */
    RequestBillingJPanel(JPanel userProcessContainer, UserAccount userAccount, Enterprise enterprise, PatientTreatmentWorkRequest workRequest) {
        initComponents();
        this.jPanel = userProcessContainer;
        this.usrAcnt = userAccount;
        this.entrpz = enterprise;
        this.pntTrtmntWrkReq = workRequest;
        pplTbl();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        fstNmTxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lstNmTxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        asgndDocTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        pntIdTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        consChrgTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        medChrgTxt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        labChrgTxt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        miscChrgTxt = new javax.swing.JTextField();
        sndBillReqBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Billing Request");
        add(jLabel1);
        jLabel1.setBounds(251, 16, 178, 29);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("PATIENT INFORMATION");
        add(jLabel6);
        jLabel6.setBounds(269, 89, 146, 15);

        fstNmTxt.setEditable(false);
        add(fstNmTxt);
        fstNmTxt.setBounds(200, 122, 131, 23);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("First Name :");
        add(jLabel7);
        jLabel7.setBounds(124, 124, 73, 15);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Last Name :");
        add(jLabel10);
        jLabel10.setBounds(365, 124, 71, 15);

        lstNmTxt.setEditable(false);
        add(lstNmTxt);
        lstNmTxt.setBounds(440, 122, 131, 23);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Assigned Doctor :");
        add(jLabel8);
        jLabel8.setBounds(87, 162, 106, 15);

        asgndDocTxt.setEditable(false);
        add(asgndDocTxt);
        asgndDocTxt.setBounds(200, 160, 130, 23);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Patient Id:");
        add(jLabel2);
        jLabel2.setBounds(371, 162, 66, 15);

        pntIdTxt.setEditable(false);
        add(pntIdTxt);
        pntIdTxt.setBounds(440, 160, 131, 23);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("BILLING INFORMATION");
        add(jLabel3);
        jLabel3.setBounds(273, 225, 146, 15);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Consultaion Charges (USD) :");
        add(jLabel4);
        jLabel4.setBounds(205, 258, 173, 21);

        consChrgTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consChrgTxtActionPerformed(evt);
            }
        });
        add(consChrgTxt);
        consChrgTxt.setBounds(388, 258, 82, 23);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Medication Charges (USD):");
        add(jLabel5);
        jLabel5.setBounds(215, 325, 164, 21);
        add(medChrgTxt);
        medChrgTxt.setBounds(388, 323, 82, 23);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Lab Test Charges (USD) :");
        add(jLabel11);
        jLabel11.setBounds(220, 290, 152, 21);

        labChrgTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                labChrgTxtActionPerformed(evt);
            }
        });
        add(labChrgTxt);
        labChrgTxt.setBounds(388, 290, 82, 23);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Miscellaneous Charges (USD):");
        add(jLabel12);
        jLabel12.setBounds(199, 361, 182, 17);
        add(miscChrgTxt);
        miscChrgTxt.setBounds(388, 359, 82, 23);

        sndBillReqBtn.setBackground(new java.awt.Color(0, 153, 255));
        sndBillReqBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        sndBillReqBtn.setText("Send Billing Request");
        sndBillReqBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sndBillReqBtnActionPerformed(evt);
            }
        });
        add(sndBillReqBtn);
        sndBillReqBtn.setBounds(277, 410, 159, 32);

        backBtn.setBackground(new java.awt.Color(0, 153, 255));
        backBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        backBtn.setText("<<Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn);
        backBtn.setBounds(45, 25, 90, 29);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/billing6.gif"))); // NOI18N
        jLabel9.setToolTipText("");
        jLabel9.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(jLabel9);
        jLabel9.setBounds(158, 5, 560, 490);
    }// </editor-fold>//GEN-END:initComponents

    private void labChrgTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_labChrgTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_labChrgTxtActionPerformed

    private void consChrgTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consChrgTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_consChrgTxtActionPerformed

    private void sndBillReqBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sndBillReqBtnActionPerformed
        String consultationCharge = consChrgTxt.getText().trim();
        String labChargesStr = labChrgTxt.getText();
        String miscellaneouschargesStr = miscChrgTxt.getText();
        String medicationChargesStr = medChrgTxt.getText();
        if (consultationCharge.equals("") || labChargesStr.equals("") || miscellaneouschargesStr.equals("") || medicationChargesStr.equals("")) {
            JOptionPane.showMessageDialog(null, "All fields are mandatory");
        } else {
            
            try {
                Double.parseDouble(consultationCharge);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Please provide a Numeric value for Consultation Charges");
                return;
            }
            
            try {
                Integer.parseInt(labChargesStr);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Please type a Numeric value for Lab Charges");
                return;
            }
            try {
                Integer.parseInt(miscellaneouschargesStr);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Please type a Numeric value for Miscellaneous charges");
                return;
            }
            try {
                Integer.parseInt(medicationChargesStr);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Please type a Numeric value for Medication charges");
                return;
            }
            double labCharges = Double.parseDouble(labChargesStr);
            double miscellaneouscharges = Double.parseDouble(miscellaneouschargesStr);
            double medicationCharges = Double.parseDouble(medicationChargesStr);
            double billingAmount = labCharges + cnsltChrg + medicationCharges + miscellaneouscharges;
            //request.setBillAmount(billingAmount);

            int dialogResult = JOptionPane.showConfirmDialog(null, "Do you want to proceed?");
            if (dialogResult == JOptionPane.YES_OPTION) {
                pntTrtmntWrkReq.setStatus("Consultation Completed");

                AccountantBillingRequest accountantBillingRequest = new AccountantBillingRequest();
                accountantBillingRequest.setBillingAmt(billingAmount);
                //  accountantBillingRequest.setPatientId(Integer.parseInt(txtPatientId.getText()));

                accountantBillingRequest.setSender(usrAcnt);
                accountantBillingRequest.setStatus("Sent");

                accountantBillingRequest.setPatient(pntTrtmntWrkReq.getPat());

                Organization org = null;
                for (Organization organization : entrpz.getOrgDir().getOrganizations()) {

                    if (organization instanceof AccountantOrganization) {
                        org = organization;
                        break;
                    }
                }
                if (org != null) {

                    org.getWrkQ().getWorkRequests().add(accountantBillingRequest);
                    usrAcnt.getWrkQ().getWorkRequests().add(accountantBillingRequest);

                }

                JOptionPane.showMessageDialog(null, "Prescription submitted successfully");
                sndBillReqBtn.setEnabled(false);
            }
        }

    }//GEN-LAST:event_sndBillReqBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        jPanel.remove(this);
        Component[] componentArray = jPanel.getComponents();
        Component component = componentArray[componentArray.length - 1];
        DoctorWorkAreaJPanel dwjp = (DoctorWorkAreaJPanel) component;
        dwjp.pplReqTbl();
        CardLayout layout = (CardLayout) jPanel.getLayout();
        layout.previous(jPanel);
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField asgndDocTxt;
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField consChrgTxt;
    private javax.swing.JTextField fstNmTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField labChrgTxt;
    private javax.swing.JTextField lstNmTxt;
    private javax.swing.JTextField medChrgTxt;
    private javax.swing.JTextField miscChrgTxt;
    private javax.swing.JTextField pntIdTxt;
    private javax.swing.JButton sndBillReqBtn;
    // End of variables declaration//GEN-END:variables

    private void pplTbl() {


        fstNmTxt.setText(pntTrtmntWrkReq.getPat().getPatFrstNm());
        lstNmTxt.setText(pntTrtmntWrkReq.getPat().getPatLstNm());
        pntIdTxt.setText(String.valueOf(pntTrtmntWrkReq.getPat().getPatId()));
        asgndDocTxt.setText(pntTrtmntWrkReq.getAssignedDoc().getEmp().getEmpName());
        consChrgTxt.setText(String.valueOf(cnsltChrg));


    }
}
