/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.InsuranceFinanceRole;

import Business.Enterprise.Enterprise;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.InsuranceWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author dineshmurgesan
 */
public class InsuranceFinanceProcessRequest extends javax.swing.JPanel {

    private JPanel jPanel;
    private Enterprise entrpz;
    private UserAccount usrAcnt;
    private InsuranceWorkRequest isnrWrReq;

    /**
     * Creates new form InsuranceFinanceProcessRequest
     */
    InsuranceFinanceProcessRequest(JPanel userProcessContainer, UserAccount userAccount, InsuranceWorkRequest insuranceWorkRequest, Enterprise enterprise) {
        initComponents();
        this.jPanel = userProcessContainer;
        this.entrpz = enterprise;
        this.usrAcnt = userAccount;
        this.isnrWrReq = insuranceWorkRequest;
        plcyNumTxt.setText(insuranceWorkRequest.getPlcyNo());
        ssnTxt.setText(insuranceWorkRequest.getSsn());
        plcyNmTxt.setText(insuranceWorkRequest.getPlcyNm());
        clmAmntTxt.setText(String.valueOf(insuranceWorkRequest.getClaimAmt()));
        billingAmntTxt.setText(String.valueOf(insuranceWorkRequest.getBillAmt()));
        cvgTxt.setText(String.valueOf(insuranceWorkRequest.getInsCust().getIns().getCvrg()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        disbrAmntBtn = new javax.swing.JButton();
        rejBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        plcyNumTxt = new javax.swing.JTextField();
        plcyNmTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        billingAmntTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        clmAmntTxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ssnTxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cvgTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        disbrAmntBtn.setBackground(new java.awt.Color(0, 153, 255));
        disbrAmntBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        disbrAmntBtn.setText("Disburse Amount");
        disbrAmntBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disbrAmntBtnActionPerformed(evt);
            }
        });
        add(disbrAmntBtn);
        disbrAmntBtn.setBounds(130, 316, 140, 32);

        rejBtn.setBackground(new java.awt.Color(0, 153, 255));
        rejBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rejBtn.setText("Reject Claim");
        rejBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rejBtnActionPerformed(evt);
            }
        });
        add(rejBtn);
        rejBtn.setBounds(291, 316, 114, 32);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Insurance Finance Request Process area ");
        add(jLabel3);
        jLabel3.setBounds(130, 17, 488, 29);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 204));
        jLabel4.setText("Policy Number");
        add(jLabel4);
        jLabel4.setBounds(154, 91, 88, 15);

        backBtn.setBackground(new java.awt.Color(0, 153, 255));
        backBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        backBtn.setText("<<Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn);
        backBtn.setBounds(10, 23, 90, 29);

        plcyNumTxt.setEditable(false);
        add(plcyNumTxt);
        plcyNumTxt.setBounds(278, 86, 116, 23);

        plcyNmTxt.setEditable(false);
        add(plcyNmTxt);
        plcyNmTxt.setBounds(278, 209, 116, 23);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("policyName");
        add(jLabel1);
        jLabel1.setBounds(172, 211, 70, 15);

        billingAmntTxt.setEditable(false);
        billingAmntTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billingAmntTxtActionPerformed(evt);
            }
        });
        add(billingAmntTxt);
        billingAmntTxt.setBounds(278, 247, 116, 23);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 204));
        jLabel6.setText("Billing Amount");
        add(jLabel6);
        jLabel6.setBounds(150, 249, 91, 15);

        clmAmntTxt.setEditable(false);
        clmAmntTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clmAmntTxtActionPerformed(evt);
            }
        });
        add(clmAmntTxt);
        clmAmntTxt.setBounds(278, 285, 116, 23);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 204));
        jLabel7.setText("Claim Amount");
        add(jLabel7);
        jLabel7.setBounds(154, 287, 85, 15);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 204));
        jLabel8.setText("SSN");
        add(jLabel8);
        jLabel8.setBounds(216, 129, 25, 15);

        ssnTxt.setEditable(false);
        add(ssnTxt);
        ssnTxt.setBounds(278, 124, 116, 23);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 204));
        jLabel9.setText("Conerage%");
        add(jLabel9);
        jLabel9.setBounds(168, 176, 71, 15);

        cvgTxt.setEditable(false);
        add(cvgTxt);
        cvgTxt.setBounds(278, 171, 116, 23);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/insurance finance.gif"))); // NOI18N
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(jLabel2);
        jLabel2.setBounds(0, 0, 720, 440);
    }// </editor-fold>//GEN-END:initComponents

    private void disbrAmntBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disbrAmntBtnActionPerformed

        disbrAmntBtn.setEnabled(true);
        int dialogResult = JOptionPane.showConfirmDialog(null, "Do you want to proceed?");
        if (dialogResult == JOptionPane.YES_OPTION) {
            isnrWrReq.setStatus("Insurance Claim Approved");
            JOptionPane.showMessageDialog(null, "Claim Approved Successfully!!!");
            disbrAmntBtn.setEnabled(false);
            rejBtn.setEnabled(false);
        }
    }//GEN-LAST:event_disbrAmntBtnActionPerformed

    private void rejBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rejBtnActionPerformed

        int dialogResult = JOptionPane.showConfirmDialog(null, "Do you want to proceed?");
        if (dialogResult == JOptionPane.YES_OPTION) {
            isnrWrReq.setStatus("Insurance Claim Rejected");
            rejBtn.setEnabled(false);
            disbrAmntBtn.setEnabled(false);
        }

    }//GEN-LAST:event_rejBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        jPanel.remove(this);
        Component[] componentArray = jPanel.getComponents();
        Component component = componentArray[componentArray.length - 1];
        InsuranceFinanceWorkAreaJPanel iwjp = (InsuranceFinanceWorkAreaJPanel) component;
        iwjp.pplTabl();
        CardLayout layout = (CardLayout) jPanel.getLayout();
        layout.previous(jPanel);
    }//GEN-LAST:event_backBtnActionPerformed

    private void clmAmntTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clmAmntTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clmAmntTxtActionPerformed

    private void billingAmntTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billingAmntTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_billingAmntTxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField billingAmntTxt;
    private javax.swing.JTextField clmAmntTxt;
    private javax.swing.JTextField cvgTxt;
    private javax.swing.JButton disbrAmntBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField plcyNmTxt;
    private javax.swing.JTextField plcyNumTxt;
    private javax.swing.JButton rejBtn;
    private javax.swing.JTextField ssnTxt;
    // End of variables declaration//GEN-END:variables
}
